version: '3'

services:
  mongodb-service-build:
    build: ./mongodb
    ports:
     - "27017:27017"
    stdin_open: true
    # tty: true

  nodeapp-service-build:
    build: ./nodejs
    ports:
     - "8000:9999"

  nginx-service-build:
    image: nginx:alpine
    ports:
     - "80:9000"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/www:/data/www"
